### ISSUE TITLE
It would be useful to be able to input html as DOM nodes instead of only strings

### ISSUE THREAD

**Issue by maparent** [shtrihstr/react-active-html#3]
See https://github.com/maparent/react-active-html/commit/16b270395842bb9d75a347969ff3344655235f54 for an implementation.
I would gladly make a PR of it if the repository were up to date.

**Comment by shtrihstr** [comment]
Hello!
Thx for suggestion, will update repo soon

**Comment by shtrihstr** [comment]
I have delivered a new version with `Node` / `NodeList` support. Please test is it what you need.

**Comment by maparent** [comment]
Thank you!
